baseURL = "https://agencemadec.netlify.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Agence MADEC"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "A Propos"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Services"
    URL = "services"
    weight = 3

    [[menu.nav]]
    name = "Quelques Realisations"
    URL = "portfolio"
    weight = 4

    [[menu.nav]]
    name = "L'Equipe"
    URL = "our-team"
    weight = 5

    [[menu.nav]]
    name = "Libre Blanc"
    URL = "pricing"
    weight = 6

    [[menu.nav]]
    name = "Blog"
    URL = "blog"
    weight = 7

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 8

# Site params
[params]
home= "Accueil"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Madec Agence à la hauteur de vos attentes"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/i-am-madec.jpg"
    icon = "tf-ion-play"
    heading = "MADEC"
    content= "Nous sommes une agence digitale à la hauteur de vos attentes"
    btn = true
    btnText="CONTACTEZ-NOUS"
    btnURL="#contact-us"

    # call to action
    [params.cta]
    enable = true
    title = "Votre Satisfaction est notre priorité"
    content = " Nous créons la qualité du produit en tenant compte de votre délai et de votre budget"
    btnURL = "#contact-us"
    btnText = "Cliquez ici pour demander un dévi"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Clients satisfaits"
        icon = "tf-ion-android-happy"
        count = "5"

        [[params.counter.counterItem]]
        title = "Projets réalisés"
        icon = "tf-ion-archive"
        count = "6"

        [[params.counter.counterItem]]
        title = "Feedback positifs"
        icon = "tf-ion-thumbsup"
        count = "5"

        [[params.counter.counterItem]]
        title = "Liked & recommendation"
        icon = "tf-ion-coffee"
        count = "100"

    # footer
    [params.footer]
        copyright = "l'Equipe Professionnelle de Madec"
        copyrightURL = "http://www.Madec.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
